-- Temporarily disable FORCE RLS to allow seeding
-- This allows the seed script to bypass RLS policies

ALTER TABLE tenants NO FORCE ROW LEVEL SECURITY;
ALTER TABLE users NO FORCE ROW LEVEL SECURITY;
ALTER TABLE accounts NO FORCE ROW LEVEL SECURITY;
ALTER TABLE auth_sessions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE widgets NO FORCE ROW LEVEL SECURITY;
ALTER TABLE meetings NO FORCE ROW LEVEL SECURITY;
ALTER TABLE sessions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE messages NO FORCE ROW LEVEL SECURITY;
ALTER TABLE knowledge_documents NO FORCE ROW LEVEL SECURITY;
ALTER TABLE knowledge_chunks NO FORCE ROW LEVEL SECURITY;
ALTER TABLE cost_events NO FORCE ROW LEVEL SECURITY;
ALTER TABLE cost_summaries NO FORCE ROW LEVEL SECURITY;
ALTER TABLE budget_alerts NO FORCE ROW LEVEL SECURITY;
ALTER TABLE ai_personalities NO FORCE ROW LEVEL SECURITY;
